# We have a conf and classes directory, add to BBPATH
BBPATH .= ":${LAYERDIR}"

# We have recipes-* directories, add to BBFILES
BBFILES += "\
	${LAYERDIR}/recipes-*/*/*.bb \
    ${LAYERDIR}/recipes-*/*/*.bbappend \
"

BBFILE_COLLECTIONS += "rz-simple-isp"
BBFILE_PATTERN_rz-simple-isp := "^${LAYERDIR}/"

LAYERDEPENDS_rz-simple-isp = "rz-drpai"
LAYERSERIES_COMPAT_rz-simple-isp = "scarthgap kirkstone"
